name: terraform-cicd


on:
  push:
    branches:
      - main

jobs:
  terraform-cicd:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: set up terraform 
        uses:  hashicorp/setup-terraform@v1
      - name: terraform innit
        run: terraform innit
      - name: terraform plan
        run: terraform plan
      - name: terraform apply
        run: terraform apply - auto-approve





  





    

