name: Node.js CI on Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    -name: set up java and maven 
     user: actions/setup-java@v3
     